### ISSUE TITLE
Final group capstone: set up Kanban board

### ISSUE THREAD

**Issue by Rhaegar121** [Rhaegar121/Car-Rental-front-end#11]
In this issue, we have completed the following tasks.

1. Created 2 repo: front end and back end for capstone project
2. Set up Kanban board for both repo: front end and back end
3. Assigned all team members to the tasks equally

There are 4 members in our team.

This is [the link of the front end project.](https://github.com/users/Rhaegar121/projects/5/views/1)

![Screenshot (82)](https://github.com/Rhaegar121/Capstone-Front-End/assets/111948881/16148a7c-5d62-449a-bad7-603c35588ad4)
<hr>

This is [the link of the back end project.](https://github.com/users/Rhaegar121/projects/6/views/1)

![Screenshot (83)](https://github.com/Rhaegar121/Capstone-Front-End/assets/111948881/1ea9efec-3c07-4f56-952d-4208179719cb)

**Comment by Meltrust** [comment]
Hi @Rhaegar121

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- All tasks have descriptions✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

- [ ] According to the project requirements:

![image](https://github.com/Rhaegar121/Capstone-Front-End/assets/57421823/891de53b-4c78-4e31-9b33-f00baf5205f4)

Some of your cards do not have the number of points for that task.  

Kindly, ensure that all cards have pointings in the title prefix [Xpt].

Remember => After adding the pointings, NO member of the team should have more than 5 points than any other member according to this:

![image](https://github.com/Rhaegar121/Capstone-Front-End/assets/57421823/6ccb622a-e8ec-451e-8720-6b48566e0f5e)

_Tip:  Count the total number of points for each team member.  Nobody should have more than 5 points of difference in the total._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Meltrust** [comment]
Hi @Rhaegar121,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  
Congratulations! 🎉 

### To highlight

- All tasks have pointings now, and they are equal✔️ 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
